# Generated by Django 2.2 on 2021-12-19 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_task_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('completion_notes', models.TextField()),
                ('date_completed', models.DateTimeField(null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='team_task_manager_app.Task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
