# Generated by Django 2.2 on 2021-11-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='favorite_books',
            new_name='favorite_by',
        ),
    ]
