# Generated by Django 3.1 on 2022-01-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_details',
            name='behavioral',
            field=models.BooleanField(null=True),
        ),
    ]
