# Generated by Django 3.1 on 2022-01-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_tracker_app', '0002_remove_company_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='role',
        ),
    ]
