# Generated by Django 3.1 on 2022-02-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_tracker_app', '0004_remove_company_location'),
        ('resume_tracker_app', '0002_auto_20220124_1116'),
        ('resume_tracker_app', '0002_auto_20220128_1434'),
        ('resume_tracker_app', '0002_interview_details_behavioral'),
    ]

    operations = [
    ]
